// src/features/wipUpdates/domain/wipUpdate.ts
// Domain model for WIP update records.
// Each record represents a single detected change for one fanfic work,
// captured at the time of a bulk check. Records are informational only —
// changes are applied to the readable immediately; these records are the inbox.

// ── Status ────────────────────────────────────────────────────────────────────

export type WipUpdateStatus = 'unread' | 'read';

// ── Domain model ──────────────────────────────────────────────────────────────

export interface WipUpdate {
  id: string;
  readableId: string;
  readableTitle: string;
  /** null for anonymous/orphaned works. */
  readableAuthor: string | null;
  /** ISO 8601 datetime. When the check was run. */
  checkedAt: string;
  status: WipUpdateStatus;

  // ── Before / after snapshot ───────────────────────────────────────────────
  // previous_* = value on the readable at the time of check.
  // fetched_*  = value extracted from AO3 (null means the field was not parsed).

  previousAvailableChapters: number | null;
  fetchedAvailableChapters: number | null;

  previousTotalUnits: number | null;
  fetchedTotalUnits: number | null;

  previousWordCount: number | null;
  fetchedWordCount: number | null;

  previousIsComplete: boolean | null;
  fetchedIsComplete: boolean | null;

  previousTags: string[];
  fetchedTags: string[];

  previousRelationships: string[];
  fetchedRelationships: string[];

  previousArchiveWarnings: string[];
  fetchedArchiveWarnings: string[];

  previousSeriesTotal: number | null;
  fetchedSeriesTotal: number | null;

  /**
   * true when the readable's status was reverted from 'completed' back to 'reading'
   * because totalUnits increased (new chapters were added to a previously "complete" count).
   */
  statusReverted: boolean;
}

// ── Input type ────────────────────────────────────────────────────────────────
// Used by createWipUpdate in the repository. id is generated by the repo;
// status defaults to 'unread'.

export type CreateWipUpdateInput = Omit<WipUpdate, 'id' | 'status'>;
