// src/features/wipUpdates/domain/wipUpdate.ts
// Domain model for WIP update records.
// Each record represents a single detected change for one fanfic work,
// captured at the time of a bulk check. Records are informational only —
// changes are applied to the readable immediately; these records are the inbox.

import type { ReadableStatus } from '../../readables';

// ── Status ────────────────────────────────────────────────────────────────────

export type WipUpdateStatus = 'unread' | 'read';

// ── Domain model ──────────────────────────────────────────────────────────────

export interface WipUpdate {
  id: string;
  readableId: string;
  readableTitle: string;
  /** null for anonymous/orphaned works. */
  readableAuthor: string | null;
  /** ISO 8601 datetime. When the check was run. */
  checkedAt: string;
  status: WipUpdateStatus;

  // ── Before / after snapshot ───────────────────────────────────────────────
  // previous_* = value on the readable at the time of check.
  // fetched_*  = value extracted from AO3 (null means the field was not parsed).

  previousAvailableChapters: number | null;
  fetchedAvailableChapters: number | null;

  previousTotalUnits: number | null;
  fetchedTotalUnits: number | null;

  previousWordCount: number | null;
  fetchedWordCount: number | null;

  previousIsComplete: boolean | null;
  fetchedIsComplete: boolean | null;

  previousTags: string[];
  fetchedTags: string[];

  previousRelationships: string[];
  fetchedRelationships: string[];

  previousArchiveWarnings: string[];
  fetchedArchiveWarnings: string[];

  previousSeriesTotal: number | null;
  fetchedSeriesTotal: number | null;

  /** ISO 8601 — the ao3UpdatedAt on the readable at the time of check. */
  previousAo3UpdatedAt: string | null;
  /** ISO 8601 — the ao3UpdatedAt returned by AO3 during this check. */
  fetchedAo3UpdatedAt: string | null;

  /**
   * true when the readable's status was reverted from 'completed' back to 'reading'
   * because totalUnits increased (new chapters were added to a previously "complete" count).
   */
  statusReverted: boolean;
}

// ── Input type ────────────────────────────────────────────────────────────────
// Used by createWipUpdate in the repository. id is generated by the repo;
// status defaults to 'unread'.

export type CreateWipUpdateInput = Omit<WipUpdate, 'id' | 'status'>;

// ── Progress callback types ───────────────────────────────────────────────────

export interface CheckProgressEvent {
  /** 1-indexed position in the queue. */
  current: number;
  /** Total works in the queue. */
  total: number;
  /** Title of the work just processed. */
  title: string;
  /** What happened to this work. */
  outcome: 'updated' | 'unchanged' | 'failed' | 'restricted';
}

export type OnCheckProgress = (event: CheckProgressEvent) => void;

// ── Scope type ────────────────────────────────────────────────────────────────

export interface CheckWipScope {
  /** Which reading statuses to include. Default: ['reading']. */
  statuses: ReadableStatus[];
  /**
   * Include works marked abandoned. Only meaningful when statuses includes
   * statuses other than 'reading'. Default: false.
   */
  includeAbandoned: boolean;
}
